### ISSUE TITLE
Service crashed. 

### ISSUE THREAD

**Issue by larsvoigt** [rabchev/brackets-server#5]
Hello,
I have tried to run brackets on our linux test server.  
At first it looks all fine -> good work from you.
So I had opened the bracket editor in my local browser. 
~~But then the service is crashed if a second user makes a request to the service.~~ 
Now it looks for a general issue.
I work with the editor and the service crashed with this exception.   

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```
Regards 
Lars

**Comment by rabchev** [comment]
Sorry to respond so much late to your issue, but I didn't have time to pay attention to this project for a while.

Did you mange to fix it? Is it still reproducible? I've never seen this error myself.

**Comment by larsvoigt** [comment]
Sorry I can´t remember for details and I never fixed the issue. Feel free to close the issue.
