### ISSUE TITLE
Socket.io version should be locked at 1.1.0

### ISSUE THREAD

**Issue by simonfan** [rabchev/brackets-server#6]
Hey, I was trying to build the project myself and found some crazyness involving socket.io connection to the server. 

I haven't yet found where exactly the problem is, but by locking my socket.io version to 1.1.0 and running grunt build again in order to reminify the js of brackets solved the issue. Thus it must be related to the version (1.3.5 was the one that was being installed).

I'll continue to look into this.

**Comment by rabchev** [comment]
Let me know if I can help.

**Comment by rabchev** [comment]
Done
