### ISSUE TITLE
"Unknown internal error" when trying to install extensions

### ISSUE THREAD

**Issue by johnnymn** [rabchev/brackets-server#8]
The error message shows up when trying to install extensions, the server is running in a Debian based distro. Im unnable to reproduce the bug in my Windows 7 machine.

**Comment by rabchev** [comment]
Does it happen for some specific extension or all extensions? 

You could also check the permissions of Brackets support directory, it requires write permissions to be able to install user extensions.  Please see --supp-dir option. 

Also, if the extension uses NodeJS domain, it must be explicitly allowed with -d option.

**Comment by johnnymn** [comment]
Folder permissions problem - solved
